text_to_write=(input("Enter text to Write to the file:"))
file1=open("output.txt","w")
file1.write(text_to_write + "\n")
file1.close()
print("Data successfully written to output.txt ")
text_to_append=(input("Enter additional text to append:",))
file2=open("output.txt","a")
file2.write(text_to_append + "\n")
file2.close()
print("Data successfully appended.")
print("\nFinal content of output.txt:")
file3=open("output.txt","r")
print(file3.read())
file3.close()